-- Initial manual setup required for each environment in target Snowflake account
-- Required before the deployment will work
-- The deployment uses <env>_SCHEMACHANGE_USER for acting on 
--  target environment in Snowflake account

-- variables --
SET TARGET_ENVIRONMENT = 'PRD'; -- DEV, TST

SET SCHEMACHANGE_USER = $TARGET_ENVIRONMENT || '_SCHEMACHANGE_USER';
SET SCHEMACHANGE_ROLE = 'FR_' || $TARGET_ENVIRONMENT || '_SCHEMACHANGE';
SET SCHEMACHANGE_WAREHOUSE = 'WH_' || $TARGET_ENVIRONMENT || '_SCHEMACHANGE';
SET HISTORY_TABLE = 'SCHEMACHANGE.' || $TARGET_ENVIRONMENT || '_CHANGE_HISTORY';

USE ROLE ACCOUNTADMIN;

-- user and role --
CREATE USER IF NOT EXISTS IDENTIFIER($SCHEMACHANGE_USER)
    LOGIN_NAME = $SCHEMACHANGE_USER
    DISPLAY_NAME = $SCHEMACHANGE_USER


    PASSWORD = 'Password@1';

CREATE ROLE IF NOT EXISTS IDENTIFIER($SCHEMACHANGE_ROLE);
GRANT ROLE ACCOUNTADMIN TO ROLE IDENTIFIER($SCHEMACHANGE_ROLE);
GRANT ROLE IDENTIFIER($SCHEMACHANGE_ROLE) TO USER IDENTIFIER($SCHEMACHANGE_USER);

-- schemachange warehouse --
CREATE WAREHOUSE IF NOT EXISTS IDENTIFIER($SCHEMACHANGE_WAREHOUSE)
WITH INITIALLY_SUSPENDED = TRUE
WAREHOUSE_SIZE = XSMALL
AUTO_SUSPEND = 60;

-- schemachange history table --
USE DATABASE ADMIN_DB;
CREATE TABLE IF NOT EXISTS IDENTIFIER($HISTORY_TABLE)
(
    VERSION VARCHAR
   ,DESCRIPTION VARCHAR
   ,SCRIPT VARCHAR
   ,SCRIPT_TYPE VARCHAR
   ,CHECKSUM VARCHAR
   ,EXECUTION_TIME NUMBER
   ,STATUS VARCHAR
   ,INSTALLED_BY VARCHAR
   ,INSTALLED_ON TIMESTAMP_LTZ
);

-- To verify what has been created
-- DESCRIBE USER IDENTIFIER($SCHEMACHANGE_USER);
-- SHOW GRANTS ON USER IDENTIFIER($SCHEMACHANGE_USER);
-- SHOW GRANTS ON ROLE IDENTIFIER($SCHEMACHANGE_ROLE);
-- DESCRIBE TABLE IDENTIFIER($HISTORY_TABLE);
