-- Script for key rotation for '<TARGET_DEV>_<SERVICE>_USER

USE ROLE ACCOUNTADMIN;

SET ENV = '<TARGET_ENV>';
SET SERVICE = '<SERVICE>';
SET USER = $ENV || '_' || $SERVICE || '_USER';

ALTER USER IDENTIFIER($USER) SET RSA_PUBLIC_KEY = '<ROTATED_PUBLIC_KEY>';
