name: Deploy Snowflake Objects to dev

on:
  # Trigger on push for the dev branch
  push:
    branches:
      - dev
      
jobs:
  deploy-snowflake-changes-job:
    runs-on: ubuntu-latest
    environment: DEV

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Python 3.8.x
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.8.x

      # creating a dynamic file in from the private key stored in git secret and providing access only
      # to owner so chmod 600
      - name: Decrypt RSA key
        run: |
          echo hello  > ./config/file.txt
          echo "${{ secrets.SNOWFLAKE_PRIVATE_KEY }}"  > ${{ secrets.SNOWFLAKE_PRIVATE_KEY_PATH}}
          chmod 600 ${{ secrets.SNOWFLAKE_PRIVATE_KEY_PATH}} 


      - name: Run schemachange
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER:  ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
          SNOWFLAKE_WAREHOUSE:  ${{ secrets.SNOWFLAKE_WAREHOUSE }}
          SNOWFLAKE_DATABASE: SCHEMACHANGE
          # SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          ENV:  ${{ vars.ENV }}

          SNOWFLAKE_PRIVATE_KEY_PATH: ${{ secrets.SNOWFLAKE_PRIVATE_KEY_PATH}}
          SNOWFLAKE_PRIVATE_KEY_PASSPHRASE: ${{ secrets.SNOWFLAKE_PRIVATE_KEY_PASSPHRASE}}
 
        run: |
          echo "****************"
          echo "Variable check"
          echo $ENV

          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          python --version
          echo "Step 1: Installing schemachange"
          pip install schemachange==3.7.0

          echo "ACCOUNT: $SNOWFLAKE_ACCOUNT"

          
          echo "Step 2: Running schemachange"
          schemachange deploy -f $GITHUB_WORKSPACE/migrations -a $SNOWFLAKE_ACCOUNT -u $SNOWFLAKE_USER -r $SNOWFLAKE_ROLE -w $SNOWFLAKE_WAREHOUSE -d $SNOWFLAKE_DATABASE -c $SNOWFLAKE_DATABASE.SCHEMACHANGE.CHANGE_HISTORY_$ENV --create-change-history-table  

        # Remove the private key file after use    
      - name: Clean up private key file
        run: rm -f rsa_key.p8